AppleALC/kern_alc.cpp
Hi. I found a minor typo. It doesn't really matter though... Please fix it anyway. :D
Best regards,
Angel
=> Fixed a small typo.

Resources/PinConfigs.kext/Contents/Info.plist
Fixed certain issues and disabled unused nodes.
=> update ConfigData for MSI GP62 Leopard Pro for certain issues

Resources/CA0132/Info.plist, Resources/CX20722/Info.plist, Resources/CX20724/Info.plist, Resources/CX20751_2/Info.plist, Resources/IDT92HD71B7X/Info.plist
The previous PR is corrupted and I cannot remove the commits from it. 
So I create a new PR instead. Sorry for the inconvenience.
=> Fix the type of `MinKernel` in bundles: IDT92HD71B7X, CA0132, CX20722, CX20724, CX20751_2.

Resources/CX8200/Info.plist
Like the title.  Bug discovered in ProBook G4 use/testing.
=> fix volume control for CX8200 with Wern Apfel patch from CX20724

Resources/CX20756/PlatformsID.xml, Resources/PinConfigs.kext/Contents/Info.plist
Also in order for the External Mic to work, it needs Codec Commander with a custom SSDT file. Attached below if needed.
[SSDT-CX20756.dsl.zip](https://github.com/acidanthera/AppleALC/files/2475793/SSDT-CX20756.dsl.zip)
=> Fixed CX20756 files for InsanelyDeepak version

Resources/Controllers.plist
Add support for HDMI Audio of Alienware Alpha GTX860M
=> Add support for HDMI Audio of Alienware Alpha GTX860M

Resources/CX8050/Info.plist
Fixes speaker volume slider on Asus Vivobook X510UNR
=> [PATCH] Apply Wern Apfel patch to CX8050

Resources/VT1705/Info.plist
=> Fix Typo Binary for VT1705

Resources/Controllers.plist, Resources/PinConfigs.kext/Contents/Info.plist
Fix Typo / Update Pinconfig ALC294 layout21
=> Fix Typo/Update Pinconfig ALC294 layout21 by Andres and Add HDAController patch for WhiskeyLake Notebook

Resources/Controllers.plist
Needs testing, volume and balance seems to be unstable while listening to Spotify
=> Added AMD Zen 2 controller patches, thanks to @Algreyy (Needs testing)

Resources/ALC256/Info.plist
Fixed string Platforms97.xml.zlib Realtek ALC256 layoutid:97
=> 9-26-2019 Fixed string Platforms97.xml.zlib Realtek ALC256 layoutid:97

Resources/PinConfigs.kext/Contents/Info.plist
updated /PinConfigs.kext/Contents/Info.plist
=> added 01470C02 node for headphone behavoir to fix sleep after wake

Resources/Controllers.plist
Adds the Intel 400 series controller (Comet Lake)
=> Add the 400 series controller

Resources/ALC256/Platforms97.xml, Resources/PinConfigs.kext/Contents/Info.plist
I contacted dalian and he said its ok.
=> Added 4 channel support and fixed mute button to ALC256 layout 97

Resources/ALC230/Platforms20.xml
Hi
I fixed the mute button on Lenovo Ideapad 320 with ALC230 and layout id 20 
Thx
=> Add mute button to ALC230 layout 20

Resources/ALC230/Platforms13.xml
Hi
I fixed the mute button on Lenovo Ideapad 320 with ALC230 and layout id 13
also, I tried to fix no sound after using mic (like Siri) after sleep with layout 20 but got no luck 
any idea?
Thx
=> Add mute button to ALC230 layout 13

Resources/Controllers.plist
Adds the PCH-H Comet Lake PCH-H controller.
=> Rename 400 series LP controller, add 400 series PCH-H controller

Resources/ALCS1200A/Info.plist, Resources/ALCS1200A/Platforms11.xml, Resources/ALCS1200A/layout50.xml, Resources/PinConfigs.kext/Contents/Info.plist
Modify the content of ALCS1200A with ID 11
=> Fix ALCS1200A lost ID 11

AppleALC.xcodeproj/project.pbxproj, AppleALC/ALCUserClient/ALCUserClient.cpp, AppleALC/ALCUserClient/ALCUserClient.hpp, AppleALC/ALCUserClientProvider/ALCUserClientProvider.cpp, AppleALC/ALCUserClientProvider/ALCUserClientProvider.hpp, AppleALC/Info.plist, AppleALC/UserKernelShared.h, AppleALC/kern_alc.cpp, AppleALC/kern_alc.hpp, AppleALC/kern_resources.hpp, AppleALC/kern_start.cpp, alc-verb/hdaverb.h, alc-verb/main.c
=> Support for sending hda-verbs from user-space

Resources/PinConfigs.kext/Contents/Info.plist
=> Fix PinConfigs ALC662v3 for Lenovo M415-D339

Resources/ALC289/Platforms87.xml, Resources/ALC289/layout87.xml, Resources/PinConfigs.kext/Contents/Info.plist
In general, a few updates to fix the microphone.
---
Good:
- Switch mode audio output (e.g. between int & jack audio)
- Balance sound output L/R
- Mute control
- Internal speaker
- Internal mic
Still need to fix:
- Ext mic A.K.A Headset mic (3.5mm combojack audio)
- A littlebit crackling (almost unhearable/unnoticeable, only IEM on my test. acceptable in my ears opinion:) )
---
=> Improvement Realtek ALC289 layout-id 87 for Alienware m15

Resources/CX20724/Info.plist, Resources/CX20724/PlatformsID.xml, Resources/CX20724/PlatformsM.xml
This works for both layout3 and layout13.
=> Fix mute on  Conxexant CX 20724 by Human7900

AppleALC.xcodeproj/project.pbxproj, AppleALC/AppleALC-Info.plist, AppleALC/AppleALCU-Info.plist, AppleALC/kern_alc.cpp, AppleALC/kern_alc.hpp, AppleALC/kern_resources.hpp, AppleALC/kern_start.cpp, README.md, Resources/Kexts.plist, Resources/PinConfigs.kext/Contents/Info.plist
Adds patching support for 64-bit 10.6 and 10.7.
=> Support for 64-bit 10.6 and 10.7

Resources/PinConfigs.kext/Contents/Info.plist
To make it work when wake from sleep, thank you~
=> Update WakeConfigData for ALC255 layout-id 96

Resources/PinConfigs.kext/Contents/Info.plist
added verb 01B70C02 to WakeConfigData to set EAPD for speaker node
=> Try to solve wake up mute for GP75 9SD

Resources/PinConfigs.kext/Contents/Info.plist
ALC662v3 for Lenovo M415-D339
Changelog:
Device: Mic In -> Line In
Connector: Unknown -> Other Digital
Port: Fixed -> Jack
=> Fix PinConfigs Device and Port in ALC662v3

Resources/PinConfigs.kext/Contents/Info.plist
disable some NID, fix sounds issues
=> fix 583 pinconfig for nuc9

Resources/ALC255/Platforms22.xml, Resources/ALC255/layout22.xml, Resources/PinConfigs.kext/Contents/Info.plist
Realised from my last layout changes that there was an issue with the microphone, this has now been solved
=> ALC255 Layout 22 Mic Fix by Feartech

Resources/PinConfigs.kext/Contents/Info.plist
- Fixed audio not working after reboot from windows with realtek driver installed
=> Updated PinConfig for layout 11 ALC897
