ResourceConverter/main.mm
Fixed compilation error when more than one codec in the Resources directory.
Tested with one and multiple resources.
Спасибо за kext!
=> fix compilation error when more than one resource

Resources/ALC888/Info.plist
Prevents codec sleep and clicking on iMac models. Patches works for 10.9 10.10 10.11
=> ALC888 no sleep, no click patch.

AppleALC/kern_resources.cpp, Resources/ALC888/Info.plist
Hi, first off, brilliant work.  I love the method you're using, integrating all the little patches specific to this or that hardware and patching the right Apple extensions as needed.  This is basically the audio driver of (I imagine) most people's dreams.  
Anyway, I am running a C612 (same audio subsystem as X99) with an ALC888VD, Revision 0x100302.  I'm running the latest release version of macOS Sierra, and there doesn't appear to be any changes necessary to operate this revision.  Everything works flawlessly, I've tested all the inputs and outputs.  I think it is safe to pull this trivial patch.  
Thanks again, great work.
=> Added ALC888 Revision 100302 to Info.plist.

AppleALC/kern_alc.cpp, Changelog.md
Hi. I think we may remove these kinds of useless complaints in normal cases. As for normal users I suppose they are just harmless and I propose to remove them.
=> Remove redundant logs of AppleHDA and AppleHDAController if debug mode not enabled.

Resources/ALC221/Info.plist
added support for my HP EliteDesk 800 G2 TWR. All I had to do is edit `Resources/ALC221/Info.plist` and add my codec revision `<integer>1048835</integer>` on the file. I compiled it and I have been using it happily for many weeks now.
=> add codec revision 0x100103 (1048835) for ALC221

Resources/ALC257/Info.plist
The original patch replaces `11D4198B` into the ALC257 codec `EC100257`. It does not work for ALC257 codec used by ThinkPad T480s and T480 ([source](https://www.hackintosh-forum.de/index.php/Thread/37614-Lenovo-T480/?postID=434080#post434080)). There will be no audio devices at all.
ALC257 is very similar to ALC256 and I checked the patch in ALC256 which replaces `11D41984` instead. I also used this patch for ALC257, which now works perfectly on my ThinkPad T480s.
This pull request changes the patch for ALC257 to replace `11D41984` instead of `11D4198B`.
=> Fix AppleHDA patch for ALC257

AppleALC/kern_alc.cpp, AppleALC/kern_alc.hpp, Changelog.md
I've encountered some issues with HDMI audio on older NVIDIA cards (GT218), likely caused by some incompatibility with AppleHDA, resulting in kextd stalls and nonworking HDMI audio. Applying this property "no-alc-controller" to the HDAU device with any non-zero value would prevent AppleALC from applying HDAU fixes to that controller if needed.
=> Add no-alc-controller property for excluding specific HDMI audio controllers

Resources/CX20751_2/Info.plist
Update Revision 0x100001 for CX20751/2 (Toshiba Kira 107)
=> Update Revision for CX20751/2

Resources/ALC1220/Info.plist
This PR fixes an issue where audio wasn't available after sleep on ALC1220 on 10.14.4.
=> Fix ALC1220 audio after sleep.

Resources/PinConfigs.kext/Contents/Info.plist
Previously sound would not restore after sleep. Now, sound works fine even after sleep. Everything seems to be working fine and it also builds properly.
FYI this layout is also compatible with MSI GS65 (for anyone who looks for this layout).
=> Added wake verb for ALC1220 for MSI P65 Creator / MSI GS65.

Resources/ALC700/Platforms11.xml, Resources/PinConfigs.kext/Contents/Info.plist
SPDIF fixed with a new engine stream. HP jack fixed with custom verb init.
=> ALC700: fix HP and SPDIF outputs

Resources/PinConfigs.kext/Contents/Info.plist
The pincomplex verb works for both speakers (intSpeaker, Headphones), but strangely not the Internal or LineIn microphone.
The pincomplex is already set in the pinconfig, however it doesn't persist after sleep. As a workaround, I've added the necessary verbs to WakeConfigData. If this is not correct, please let me know.
=> fix layout 13 CX8050 microphone after sleep

AppleALC/kern_alc.cpp
In Haswell chipset, if "no-hda-gfx" is used to fix the kernel panic issue, all audio are disabled. This commit makes the audio work.  Audio through IGPU will still not work though. I've tested with Gigabyte Z97 motherboard, Intel i7-4790 CPU, ALC888 chipset, macOS 10.15.0, audio port on back panel & front panel with an analog headset, and Clover config.plist
<key>Properties</key>
<dict>
<key>PciRoot(0x0)/Pci(0x1b,0x0)</key>
<dict>
<key>layout-id</key>
<integer>1</integer>
<key>no-hda-gfx</key>
<string>1</string>
</dict>
</dict>
=> Enable analog to digital when using "no-hda-gfx"

Resources/Controllers.plist
Fix the loss of HDMI sound after the  first boot / rebooting the system (without this edit, you should have unplug /plug the HDMI cable for fix)
=> add support intel NUC7 HDMI audio device-id 719d

Resources/ALC700/Platforms11.xml, Resources/ALC700/layout11.xml, Resources/PinConfigs.kext/Contents/Info.plist
Currently the back port (labeled line out, usually connected to speakers)
takes priority over the front port (labeled microphone). That means if
both ports are plugged in, the back port takes priority even though it
makes more sense to have the back port always plugged in to a speaker and
the front port connected to something temporary like headphones. In
practice either port can work, but cable management can get ugly.
This is due to the fact that OSX prioritizes Line Out > HP > Speakers.
The default pin config labels the back port as Line Out but that doesn't
seem to be correct as it has an active amp attached which makes more sense
as a speaker output (line out is supposed to not have any amps). Therefore
this patch re-labels node 0x1B to be a "Speaker" port instead.
OSX also has no …
=> ALC700: fixed speaker/headphone priority

Resources/Controllers.plist
Seems to work great and no surprises:  just inject a layout-id of 1 like other intel PCH controllers and AppleALC will figure out which codec to use automatically (so just like the other Intel PCHs).  
The patch is identical to the 200 series PCH patches, except that the device id is A1F0 vs the 200 series' A2F0.  Tested with a C621 motherboard (a Supermicro X11DAi-N) using a Realtek ALC888 (I believe those, as well as ALC887 and ALC1220/B codecs are typically what get paired with a C621 chipset).
=> Added support for Intel C620 series PCH Audio

AppleALC/kern_alc.cpp, AppleALC/kern_alc.hpp, AppleALC/kern_resources.hpp, Changelog.md, Resources/Kexts.plist
This is a simple workaround for bug #422 - AppleALC working intermittently.
I tried different places where to put this delay, and AppleHDAController::start seems to be the best one.
=> Support optional configurable delay before start of AppleHDAController

Resources/PinConfigs.kext/Contents/Info.plist
These two codecs previously required CodeCommander.kext to have working microphones, this PR fixes that dependency so these two codecs work without it now.
- Updated ConfigData & Added WakeConfigData to fix CX20751/2 LineIn
- Updated ConfigData & Updated WakeConfigData to fix ALC221 LineIn(s)
=> Fix Conexant CX20751/2 LineIn & Realtek ALC221 LineIn(s)

Resources/ALC269/Platforms22.xml, Resources/PinConfigs.kext/Contents/Info.plist
Fix Headphone NodeID ALC269VC Veritron Z4640G by Andres ZeroCross
=> Fix Headphone NodeID ALC269VC Veritron Z4640G

Resources/PinConfigs.kext/Contents/Info.plist
added wakeconfigdata for ALC230 into Resources/PinConfigs.kext/Contents/Info.plist 
to fix sleep after wake for headphone Linein with battery
=> added wakeconfigdata for ALC230

Resources/CX8050/Info.plist
The CX8050 has an implicit audio selector in Audio Input nodes 0x13 and 0x14 with 3 connections, each having one input amplifier. The internal mic is connected to connection index 1 of node 0x13. To adjust the internal mic gain, volume of amplifier index 1 has to be changed. 
According to intel HDA spec, multiple connections are only valid for Mixer and Selector nodes. Hence, the Apple HDA driver adjusts amp gain only for the first index of input node.
This patch modifies the driver to include connection index for input node as well while adjusting gain which fixes the issue.
=> Add patch to fix internal mic gain adjustment

Resources/Controllers.plist
Patch based on this commit: 9c84c655f86b4c46e077538f85c19459dcdad8de (Thanks @lvs1974!)
Corrects PCH-LP audio with 02C8 mobile controllers, tested and working on my Yoga (10th gen Comet Lake).
=> Corrects 400 series PCH-LP

Resources/Controllers.plist
According to https://github.com/torvalds/linux/commit/491f833134ac474434e1c950925c58b2ac13ca72, the Ice Lake audio controller is still based on Skylake feature set. Currently waiting for feedback.
=> Add Icelake Smart Sound Technology Audio Controller

Resources/Controllers.plist
Some 400 series chipsets' device is `0xA3F0`
There are four chipsets with 0xA3F0 device that I know:
- MSI H410M(-A) PRO
- MSI MAG B460M MORTAR (WIFI)
- ASRock B460M Pro4
- ONDA B460SD4
It's tested and working on my MSI H410M-A PRO.
=> Add 0xA3F0 device in 400 series chipsets

Resources/Controllers.plist
This fix resolves a no audio issue for a few people with Ice Lake laptops.  I don't have the hardware to test this myself, but I have received multiple confirmations that it's working including input from @m0d16l14n1, @Ardentwheel, and a thread on [InsanelyMac](https://www.insanelymac.com/forum/topic/345440-applealc-alc289-on-ice-lake-dell-7390-2-in-1-i7-1065g7-with-patch-from-fewtarius-works/).  This is the same patch @lvs1974 created for Comet Lake, simply applied to the Ice Lake controller.  Also pinging @zhen-zen for feedback, as I want to make sure this doesn't accidentally break something with Ice Lake.  Before issuing a pull request I wanted to make sure it was working on at least two different model devices, we've confirmed success with two Hasee X57S1 laptops, and a Dell 7390.
=> Ice Lake patch - Resolves no audio issues for multiple users.

Resources/PinConfigs.kext/Contents/Info.plist
- Corrects the configuration needed for the ALC285 on the Lenovo X1 Carbon Gen 6 (X1C6) to eliminate "scratchy" audio, fix jacksense, and audio on wake from sleep as described and tested here: https://github.com/tylernguyen/x1c6-hackintosh/issues/75
Most work & credit by & to @fewtarius who did the work and gave hope to some poor hackintoshers out there! 👍
=> Fix LayoutId 21 for ALC285 on X1C6 (by @fewtarius)

Resources/ALC230/Platforms13.xml, Resources/ALC230/Platforms20.xml, Resources/PinConfigs.kext/Contents/Info.plist
=> Add Jack Sense and EAPD support to ALC230 layout 13 & 20 and add WakeConfigData to layout 13

Resources/CX20751_2/Info.plist
Unfortunately Vasishath's patches to fix microphone gain slider no longer work in Big Sur.
I checked what's changed using IDA and ported these patches to work in Big Sur.
Now the microphone gain slider works again :)
NOTE: this is relevant only for CX20751_2 and Big Sur.
Thanks and happy new year,
Luca
=> [CX20751_2] Fixed mic gain slider in Big Sur

Resources/Controllers.plist
Although this controller is supported, we need a patch to enable HDMI audio.
=> Add controller patch for 100 Series (8086:A170) controller

Resources/Controllers.plist
Hello,
My device (Acer VX5-591G) with device-id 0xA171 need a patch that replace `0E0000BE020000004889DF` to `0E0000B8709D0000EB0690` for HDMI audio to work.
=> Fixed HDMI Audio 0xA171 for Acer VX5-591G

Resources/Controllers.plist
We should seperate laptop and desktop model for Nuc8i7HVK with 8086:A171, in order to use Digital audio again.
This solves the bug report https://github.com/acidanthera/bugtracker/issues/1761, where the bug is brought by https://github.com/acidanthera/AppleALC/commit/2d777eab50424b4ba2829dd42da94ecaf98f0299
It follows the same existing solution manner for other computer models (different chip codec) https://github.com/acidanthera/bugtracker/issues/1661
=> Seperate laptop and desktop model for NUC 8086:A171 for Digital audio

Resources/ALC892/Platforms23.xml, Resources/ALC892/layout23.xml, Resources/PinConfigs.kext/Contents/Info.plist
Platfoms.xml:
- Add front panel connections
- Add comment
Layout.xml:
- Add Headphone
- Add comment
PinConfigs:
- Add node 25 for line in and node 27 for HP out. Used for the front-panel combo-jack port.
Tested on macOS 12.1
Thanks to all AppleALC devs
=> Add front panel connections layout 23 -  ALC892 ASRock B365 Pro4

Resources/Controllers.plist
This matches the controller patch for 8086:A170. I only tested this on macOS 11/12, but the find pattern is present in 10.11's AppleHDAController binary.
=> Remove redundant 8086:A171 controller patches

Resources/Controllers.plist
Setting the device-id to 0x9D70 doesn't work with HDMI audio. This commit replaces 0x9D70 with 0xA170 which will also fix HDMI audio. The original patch also used 0xA170.
See:
https://github.com/acidanthera/AppleALC/pull/748#issuecomment-1001042590
https://github.com/acidanthera/AppleALC/commit/d3715e08e954e1214d280ac1efbe08159f204007#commitcomment-65861080
=> Update 0xA2F0 controller patch to fix HDMI audio

AppleALC/kern_alc.cpp, Changelog.md, alc-verb/main.c
So I got the the bottom of the alc-verb issue.
The Intel HDA spec, and Apple's IOHDACodecDevice::executeVerb (and AudioDxe) all pass 4 bit verbs (0x4, 0x5, 0xC, 0xD, etc.) as 4 bits, and 12 bit verbs (0x7nn, 0xFnn) as 12 bits.
The Linux sound drivers, and Linux `alsa-tools`' `hda-verb` all represent 4 bit verbs as a 12 bit verb with 00 (0x400, 0x500, 0xC00, 0xD00, etc.).
The back end of `alc-verb` is using the Apple method, but the front end follows the Linux convention. This is not as bad as it sounds, because of the way codec verbs are eventually packed.
If we imagine using `alc-verb` or `hda-verb` to write to a 16bit processing coefficient on node 0x20 (which coefficient to use is set previously using verb 0x5, and the set value can be read afterwards using verb 0xC) with the following …
=> Update alc-verb param passing & layout of verb log

Resources/PinConfigs.kext/Contents/Info.plist
-Fixed sound not working after reboot from Windows with Realtek Driver installed
- Huge Thanks to @mikebeaton
=> Updated Pin Config for layout 16 ALC1220

Changelog.md, Resources/PinConfigs.kext/Contents/Info.plist
Changes
- Add EAPD support for speakers (Node 0x1b)
- Add WakeConfigData and WakeVerbReinit missing
Speakers audio works after sleep.
=> Fixed EAPD for layout 28 ALC269 by samcabral

Resources/PinConfigs.kext/Contents/Info.plist
Added support for sound capability from Windows booting. MSI MPG Z490 Gaming Plus Motherboard.
=> MSI MPG Z490 Gaming Plus Sound issue after booting from Windows

Changelog.md, Resources/Controllers.plist
The "old" patch sets the device id to 0x9D70 which doesn't work with HDMI audio.
This commit sets the device id to 0xA170 which also works with HDMI audio.
For more info: https://www.facebook.com/groups/hackintosch/posts/10160299439262446/
An ioreg without HDMI audio working: [jbmac.zip](https://github.com/acidanthera/AppleALC/files/8592232/jbmac.zip)
Note: 
This patch was unfortunately not tested on all macOS versions it supports (Catalina to latest macOS). Only tested on Big Sur.
I don't own this system to test all macOS versions. 
I know a new controller patch isn't supposed to get merged before testing every macOS version it supports. 
But this kind of patch was already tested on my system with 200 series (0xA2F0) HD audio, so the device id I'm setting here is indeed working and is …
=> Fix hdmi audio for 400 series 0x06C8 HD audio

Resources/ALC285/Platforms66.xml
This is an attempt to fix the mute of Internal Speaker is disabled (while the hardware supports it).
=> Fix Legion Y9000X 2020 Speaker Mute disabled issue

Resources/Controllers.plist
Tested motherboard: `Gigabyte Z790 Aorus Elite AX DDR5`
Audio Codec: `ALC897`
The default `device-id` of the audio controller is `0x7A50`. Without spoofing its device-id to `0x7AD0`, AppleALC doesn't even load.
Further proofs:
1. Default `0x7A50` as `device-id` (no spoof):
2. `0x7AD0` as `device-id` spoofed via `DeviceProperties` (ignore the wrong `layout-id` as this screenshot was taken before setting the right one):
At this point I simply copied the `600 Series(0x7AD0) PCH HD Audio` patch and replicated for the `700 series`.
I'm not quite sure that's the right approach, but from what I understood from the previous commits on this repo, to add a controller, `Resources/Controllers.plist` must be edited.
I built the kext and it works, without the `DeviceProperties` `device-id` spoof, …
=> [Controllers] Added 700 series PCH HD Audio IDs

Resources/Controllers.plist
In the function AppleHDAController::getAudioStreamLinkPositionInDMABuffer(IOHDAStream*, uint64_t*), it expects bit 0 of register 0x70 to be cleared before reading DMA position. However, for AMD, it somehow is not cleared, hence DMA position is incorrect. For now the workround is to skip that bit check.
This patch has been veried to work up to macOS Sonoma.
=> Add patch for AMD ZEN to fix microphone issue

Resources/Controllers.plist
Add in a modified version of the original VendorID check patch which matches the Sequoia AppleHDAController binary
Confirmed to be working on a `1022:1457` HDA Controller (🦀)
~~I just need people to test this on `1022:1487` and `1022:15E3` IDs~~
Confirmed working on all affected HDA controllers!
=> Fix AMD HDA Controllers on macOS Sequoia
